import { NextResponse } from "next/server";
import { db } from "../../../lib/db";
import { mapExportRow } from "../../../lib/export/mapExportRow";

export async function GET() {
  const candidates = await db.deductionCandidate.findMany({
    where:   { status: "CONFIRMED" },
    include: { transaction: true },
    orderBy: { transaction: { date: "asc" } },
  });

  if (candidates.length === 0) {
    return NextResponse.json({ error: "No confirmed candidates to export." }, { status: 404 });
  }

  const now  = new Date();
  const year = now.getFullYear();
  const generated = now.toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });

  const dataHeader = ["Date", "Merchant", "Description", "Category", "Amount (AUD)", "Evidence"];
  const rows = candidates.map((c) => {
    const row = mapExportRow(c);
    return [
      row.date,
      `"${row.merchant.replace(/"/g, '""')}"`,
      `"${row.description.replace(/"/g, '""')}"`,
      `"${row.category.replace(/"/g, '""')}"`,
      row.amount.toFixed(2),
      c.hasEvidence ? "Yes" : "No",
    ];
  });

  const total        = candidates.reduce((sum, c) => sum + Math.abs(c.transaction.amount), 0);
  const confirmed    = candidates.length;
  const withEvidence = candidates.filter((c) => c.hasEvidence).length;

  const blankRow  = [""];
  const titleRows = [
    [`"Kashio — Tax Deduction Summary ${year}"`],
    [`"Generated: ${generated}"`],
    [`"Confirmed deductions: ${confirmed}   |   Evidence attached: ${withEvidence} of ${confirmed}"`],
    blankRow,
  ];
  const totalRow  = ["", "", "", `"Total"`, total.toFixed(2), ""];
  const footerRows = [
    blankRow,
    [`"This report was generated by Kashio. Verify all deductions with your tax agent before lodging."`],
  ];

  const allRows = [
    ...titleRows,
    dataHeader,
    ...rows,
    totalRow,
    ...footerRows,
  ];

  const csv = allRows.map((r) => r.join(",")).join("\n");

  return new Response(csv, {
    headers: {
      "Content-Type":        "text/csv",
      "Content-Disposition": `attachment; filename="kashio-deductions-${year}.csv"`,
    },
  });
}
