import type { Metadata } from "next";
import { Container } from "@/components/layout/Container";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";

export const metadata: Metadata = { title: "Disclaimer" };

export default function DisclaimerPage() {
  return (
    <>
      <Navbar />
      <main className="relative z-10 pt-28 pb-20">
        <Container narrow>
          <h1 className="text-3xl font-bold mb-2" style={{ color: "var(--text-primary)" }}>
            Disclaimer
          </h1>
          <p className="text-sm mb-10" style={{ color: "var(--text-muted)" }}>
            Last updated: January 2025
          </p>

          <div className="prose-section">

            <h2>Not tax advice</h2>
            <p>
              Kashio is a software tool, not a registered tax agent. The deduction suggestions generated by Kashio are based on general ATO guidelines and automated analysis of your transaction data. They do not constitute financial, tax, or legal advice.
            </p>

            <h2>Always verify</h2>
            <p>
              Tax laws are complex and individual circumstances vary. Before lodging your tax return, always review your deductions with a registered tax agent or accountant. Do not rely solely on Kashio's suggestions when making a tax claim.
            </p>

            <h2>No guarantee of accuracy</h2>
            <p>
              While we work to make Kashio's detection engine as accurate as possible, we cannot guarantee that every suggestion is correct or complete. Some claimable expenses may not be detected, and some suggestions may not apply to your situation.
            </p>

            <h2>ATO guidelines</h2>
            <p>
              Tax rules change. Kashio's rules engine reflects general guidelines at the time of development but may not reflect the most recent ATO rulings or legislative changes. Always check the ATO website or consult a professional for the latest guidance.
            </p>

            <h2>Contact</h2>
            <p>
              For questions about this disclaimer: <a href="mailto:hello@kashio.com.au" style={{ color: "var(--accent-green)" }}>hello@kashio.com.au</a>
            </p>

          </div>
        </Container>
      </main>
      <Footer />

      <style>{`
        .prose-section h2 {
          font-size: 1.125rem;
          font-weight: 600;
          margin-top: 2rem;
          margin-bottom: 0.5rem;
          color: var(--text-primary);
        }
        .prose-section p {
          font-size: 0.9375rem;
          line-height: 1.7;
          color: var(--text-secondary);
          margin-bottom: 0.75rem;
        }
      `}</style>
    </>
  );
}
